"""add product images

Revision ID: dbc6814f40fb
Revises: c5de0993b569
Create Date: 2026-03-11 15:47:13.119177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc6814f40fb'
down_revision: Union[str, Sequence[str], None] = 'c5de0993b569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tg_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tg_file_id')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
